### ISSUE TITLE
Not a valid command: gen-idea

### ISSUE THREAD

**Issue by scalascope** [mpeltonen/sbt-idea#172] opened 2012-08-23 15:04 UTC
My plugins.sbt contains, 

``` scala
resolvers += "Typesafe Releases" at "http://repo.typesafe.com/typesafe/releases/"

addSbtPlugin("play" % "sbt-plugin" % "2.0.3")

resolvers += "Sonatype snapshots" at "http://oss.sonatype.org/content/repositories/snapshots/"

addSbtPlugin("com.github.mpeltonen" % "sbt-idea" % "1.1.0-M2-TYPESAFE")
```

when I trying to generate IntelliJ project I get

``` sbt
> gen-idea
[error] Not a valid command: gen-idea
[error] Not a valid project ID: gen-idea
[error] Not a valid configuration: gen-idea
[error] Not a valid key: gen-idea
[error] gen-idea
[error]         ^
```

**Comment by jozic** [comment] 2012-08-23 19:26
I guess that's because you use "1.1.0-M2-TYPESAFE" version, which is used by Play2.
try "idea" or "idea with-sources"

**Comment by rtyley** [comment] 2012-10-28 18:34
This (and _probably_ issue #177?) are caused by the `typesafe` fork of `sbt-idea` plugin having the same identifiers and class names as the original `mpeltonen` version but also being being critically incompatible - see Play Framework issue [#804](https://play.lighthouseapp.com/projects/82401/tickets/804-namespace-collisions-of-incompatible-typesafe-sbt-idea-fork).

I've submitted a pull request with the typesafe fork of sbt-idea to get this fixed : https://github.com/typesafehub/sbt-idea/pull/1

**Comment by mpeltonen** [comment] 2013-04-12 11:05
Play Framework issue. Fixed in latest Play version AFAIK.

**Closed as completed by mpeltonen** 2013-04-12 11:05 UTC
