### ISSUE TITLE
sbt.ResolveException with sbt 0.11.2 and sbt-idea-plugin 0.11.1-SNAPSHOT

### ISSUE THREAD

**Issue by adamw** [mpeltonen/sbt-idea#122] opened 2012-01-10 15:03 UTC
I recently updated sbt to 0.11.2, and I wanted to use some of the bug fixes that have been applied to sbt-idea-plugin (e.g. using FSC), so I'm using 0.11.1-SNAPSHOT.

In ~/.sbt/plugins/build.sbt I have:
addSbtPlugin("com.github.mpeltonen" % "sbt-idea" % "0.11.1-SNAPSHOT")

When running gen-idea, the idea project is generated, but at the end I'm getting an error:

```
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: com.github.mpeltonen#sbt-idea;0.11.1-SNAPSHOT: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn] 
[warn]  Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
[warn]      com.github.mpeltonen:sbt-idea:0.11.1-SNAPSHOT (sbtVersion=0.11.2, scalaVersion=2.9.1)
[warn] 
[error] {file:/.../}.../*:update-sbt-classifiers: sbt.ResolveException: unresolved dependency: com.github.mpeltonen#sbt-idea;0.11.1-SNAPSHOT: not found
```

**Comment by mpeltonen** [comment] 2012-01-21 08:58
This is duplicate of #119

**Closed as completed by mpeltonen** 2012-01-21 08:58 UTC
