### ISSUE TITLE
sbt.ResolveException with SBT 0.11.2

### ISSUE THREAD

**Issue by claytonwohl** [mpeltonen/sbt-idea#124] opened 2012-01-18 22:34 UTC
I'm trying to use this plugin with a brand new project. I've cleaned out ~/.sbt (except for the sbt-idea snippet in ~/sbt/plugins/build.sbt) and cleaned out the project directory (so it just has build.sbt and nothing else)

The error I get is this:

[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: com.github.mpeltonen#sbt-idea;0.11.0: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]
[warn]  Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
[warn]          com.github.mpeltonen:sbt-idea:0.11.0 (sbtVersion=0.11.2, scalaVersion=2.9.1)
[warn]
[error] {file:/C:/.../}default-215297/*:update-sbt-classifiers: sbt.ResolveException: unresolved dependency: com.github.mpeltonen#sbt-idea;0.11.0: not found

**Comment by mpeltonen** [comment] 2012-01-19 06:02
Yes, this is a known issue, and duplicate of issue #119. Currently the workaround is to run with 'gen-idea no-sbt-classifiers'.

It looks like we have to change 'no-sbt-classifiers' to be the default setting.

**Closed as completed by mpeltonen** 2012-01-19 06:02 UTC

**Comment by ijuma** [comment] 2012-01-19 07:55
I think that's a good idea.
